version: "3"
services:
  servidorweb:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./wp:/var/www/html
      - ./apache/logs:/var/log/apache2
    depends_on:
      - "bbdd"

  bbdd:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wordpressUser
      MYSQL_PASSWORD: otraSecret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PORT: 3306
    volumes:
      - ./.db_data:/var/lib/mysql
      - ./.db_backup:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: "localhost"
      PMA_USER: "root"
      PMA_PASSWORD: "secret"
    depends_on:
      - "bbdd"
    ports:
      - "8081:80"
